### ISSUE TITLE
NPM / Node version tric uses on it's container is old-ish

### ISSUE THREAD

**Issue by sc0ttkclark** [moderntribe/tric#4]
I can run `tric npm version` and get this back:

```
{ npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }
```

NPM 5.6 and Node 8.9.4 is a little older than I was hoping.

It would be great to be able to use a newer version like NPM 6.13+ or Node 12.16+

**Comment by sc0ttkclark** [comment]
https://github.com/moderntribe/tric/pull/5

**Comment by sc0ttkclark** [comment]
My work around for this is for JS tests to just use `actions/setup-node@v1`:

```
name: 'JS Tests'
on:
  pull_request:
    paths:
      - 'src/resources/js/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Run JS test suite
        run: npm run my-test-suite
```
